### ISSUE TITLE
FB Login & Signup problem

### ISSUE THREAD

**Issue by kishanankara** [RychardHunt/hodl-invest#171]
Upon hitting fb login I get this error:
<img width="1214" alt="screen shot 2018-04-17 at 12 32 37 am" src="https://user-images.githubusercontent.com/24891289/38848788-f66bebaa-41d6-11e8-9ad4-61706cebc1be.png">

Also the sign up button is not routing to any other page. 
I looked into the component login which has a sign up method, looks like it could be a redirecting issues where either the client is not able to call the server or the server is not listening to it.

**Comment by kennyzha** [comment]
we decided to not use facebook login
