### ISSUE TITLE
[Major Bug] Transaction Feature Calculation Stall

### ISSUE THREAD

**Issue by apkillion** [RychardHunt/hodl-invest#179]
Created an issue of this bug before but it was closed.  It is still a bug #147 
[https://hodl-invest.herokuapp.com/dashboard]

![buy](https://user-images.githubusercontent.com/11025435/38935272-f3d2d3ca-42eb-11e8-9aed-b448e14fad9f.png)
![sell](https://user-images.githubusercontent.com/11025435/38935274-f3de8382-42eb-11e8-9efb-45a84981ca55.png)

**Comment by RychardHunt** [comment]
resolved with #173
