### ISSUE TITLE
Bug Report(Alpha test) Total cost number not shown

### ISSUE THREAD

**Issue by xinyuche** [RychardHunt/hodl-invest#199]
I try to enter the number in the "Enter coin amount: ", the number shown below is "Total cost: $NaN" .

**Comment by RychardHunt** [comment]
Invalid. Not even a bug. 
![screen shot 2018-04-19 at 9 48 26 pm](https://user-images.githubusercontent.com/22261791/39026510-8376e248-441b-11e8-8485-eb0e7df845c7.jpg)
![screen shot 2018-04-19 at 9 48 14 pm](https://user-images.githubusercontent.com/22261791/39026511-83802fc4-441b-11e8-9403-2c55882045ac.jpg)

**Comment by RychardHunt** [comment]
Invalid. Not a bug.
![screen shot 2018-04-19 at 9 48 26 pm](https://user-images.githubusercontent.com/22261791/39026547-b03a7eca-441b-11e8-8f9e-11cc90472959.jpg)
![screen shot 2018-04-19 at 9 48 14 pm](https://user-images.githubusercontent.com/22261791/39026548-b044b034-441b-11e8-9c02-ad11b4517776.jpg)

**Comment by xinyuche** [comment]
This situation did happen, but i have closed the tab. Next time i will screen shot this. Sorry guys, My fault.
